// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as UserRoute from "@/app/(user)/page.info";
import * as UserAppLayoutCalendarRoute from "@/app/(user)/(app)/(layout)/calendar/page.info";
import * as UserAppLayoutCapsulesRoute from "@/app/(user)/(app)/(layout)/capsules/page.info";
import * as UserAppLayoutCapsulesIdRoute from "@/app/(user)/(app)/(layout)/capsules/[id]/page.info";
import * as UserAppLayoutCapsulesDateDateRoute from "@/app/(user)/(app)/(layout)/capsules/date/[date]/page.info";
import * as UserAppLayoutHomeRoute from "@/app/(user)/(app)/(layout)/home/page.info";
import * as UserLoginRoute from "@/app/(user)/login/page.info";
import * as UserPresentationRoute from "@/app/(user)/presentation/page.info";
import * as UserRegisterRoute from "@/app/(user)/register/page.info";
import * as UnlockRoute from "@/app/(user)/unlock/page.info";
import * as OfflineRoute from "@/app/~offline/page.info";
import * as AdminRoute from "@/app/admin/page.info";
import * as AdminCapsulesRoute from "@/app/admin/capsules/page.info";
import * as AdminCapsulesIdEditRoute from "@/app/admin/capsules/[id]/edit/page.info";
import * as AdminPresentationRoute from "@/app/admin/presentation/page.info";
import * as AdminUsersRoute from "@/app/admin/users/page.info";
import * as AdminUsersIdRoute from "@/app/admin/users/[id]/page.info";
import * as AdminUsersIdEditRoute from "@/app/admin/users/[id]/edit/page.info";
import * as ApiHealthRoute from "@/app/api/health/route.info";
import * as InviteCodeRoute from "@/app/invite/[code]/page.info";
import * as MiddlewareErrorEnvRoute from "@/app/middleware/error/env/page.info";
import * as MiddlewareErrorHealthCheckRoute from "@/app/middleware/error/healthCheck/page.info";
import * as SerwistPathRoute from "@/app/serwist/[path]/route.info";

export const User = makeRoute(
  "/(user)",
  {
    ...defaultInfo,
    ...UserRoute.Route
  }
);
export const UserAppLayoutCalendar = makeRoute(
  "/(user)/(app)/(layout)/calendar",
  {
    ...defaultInfo,
    ...UserAppLayoutCalendarRoute.Route
  }
);
export const UserAppLayoutCapsules = makeRoute(
  "/(user)/(app)/(layout)/capsules",
  {
    ...defaultInfo,
    ...UserAppLayoutCapsulesRoute.Route
  }
);
export const UserAppLayoutCapsulesId = makeRoute(
  "/(user)/(app)/(layout)/capsules/[id]",
  {
    ...defaultInfo,
    ...UserAppLayoutCapsulesIdRoute.Route
  }
);
export const UserAppLayoutCapsulesDateDate = makeRoute(
  "/(user)/(app)/(layout)/capsules/date/[date]",
  {
    ...defaultInfo,
    ...UserAppLayoutCapsulesDateDateRoute.Route
  }
);
export const UserAppLayoutHome = makeRoute(
  "/(user)/(app)/(layout)/home",
  {
    ...defaultInfo,
    ...UserAppLayoutHomeRoute.Route
  }
);
export const UserLogin = makeRoute(
  "/(user)/login",
  {
    ...defaultInfo,
    ...UserLoginRoute.Route
  }
);
export const UserPresentation = makeRoute(
  "/(user)/presentation",
  {
    ...defaultInfo,
    ...UserPresentationRoute.Route
  }
);
export const UserRegister = makeRoute(
  "/(user)/register",
  {
    ...defaultInfo,
    ...UserRegisterRoute.Route
  }
);
export const Unlock = makeRoute(
  "/(user)/unlock",
  {
    ...defaultInfo,
    ...UnlockRoute.Route
  }
);
export const Offline = makeRoute(
  "/~offline",
  {
    ...defaultInfo,
    ...OfflineRoute.Route
  }
);
export const Admin = makeRoute(
  "/admin",
  {
    ...defaultInfo,
    ...AdminRoute.Route
  }
);
export const AdminCapsules = makeRoute(
  "/admin/capsules",
  {
    ...defaultInfo,
    ...AdminCapsulesRoute.Route
  }
);
export const AdminCapsulesIdEdit = makeRoute(
  "/admin/capsules/[id]/edit",
  {
    ...defaultInfo,
    ...AdminCapsulesIdEditRoute.Route
  }
);
export const AdminPresentation = makeRoute(
  "/admin/presentation",
  {
    ...defaultInfo,
    ...AdminPresentationRoute.Route
  }
);
export const AdminUsers = makeRoute(
  "/admin/users",
  {
    ...defaultInfo,
    ...AdminUsersRoute.Route
  }
);
export const AdminUsersId = makeRoute(
  "/admin/users/[id]",
  {
    ...defaultInfo,
    ...AdminUsersIdRoute.Route
  }
);
export const AdminUsersIdEdit = makeRoute(
  "/admin/users/[id]/edit",
  {
    ...defaultInfo,
    ...AdminUsersIdEditRoute.Route
  }
);
export const InviteCode = makeRoute(
  "/invite/[code]",
  {
    ...defaultInfo,
    ...InviteCodeRoute.Route
  }
);
export const MiddlewareErrorEnv = makeRoute(
  "/middleware/error/env",
  {
    ...defaultInfo,
    ...MiddlewareErrorEnvRoute.Route
  }
);
export const MiddlewareErrorHealthCheck = makeRoute(
  "/middleware/error/healthCheck",
  {
    ...defaultInfo,
    ...MiddlewareErrorHealthCheckRoute.Route
  }
);
export const SerwistPath = makeRoute(
  "/serwist/[path]",
  {
    ...defaultInfo,
    ...SerwistPathRoute.Route
  }
);

export const getApiHealth = makeGetRoute(
  "/api/health",
  {
    ...defaultInfo,
    ...ApiHealthRoute.Route
  },
  ApiHealthRoute.GET
);
