import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { ReactNode, Suspense } from 'react';
import { Toaster } from 'react-hot-toast';
import ReactQueryProviders from '@/utils/providers/ReactQueryProviders';

const PontanoSansFont = localFont({
  src: '../public/fonts/Pontano_Sans/PontanoSans-VariableFont_wght.ttf',
  variable: '--font-pontano-sans',
})

const PinyonScriptFont = localFont({
  src: '../public/fonts/Pinyon_Script/PinyonScript-Regular.ttf',
  variable: '--font-pinyon-script',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {


  return (
    <html lang="fr">
      <body
        className={`${PontanoSansFont.variable} ${PinyonScriptFont.variable} antialiased`}
      >
        <ReactQueryProviders>
          <Suspense fallback={<div className="w-full h-dvh flex justify-center items-center">Loading...</div>}>
            {children}
          </Suspense>
        </ReactQueryProviders>
        <Toaster />
      </body>
    </html>
  );
}
