import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ReactNode, Suspense } from "react";
import { Toaster } from "@repo/ui/components/shadcn/sonner";
import ReactQueryProviders from "@/utils/providers/ReactQueryProviders";
import { DynamicTanstackDevTools } from "@/components/devtools/DynamicTanstackDevTools";

const PontanoSansFont = localFont({
  src: "../public/fonts/Pontano_Sans/PontanoSans-VariableFont_wght.ttf",
  variable: "--font-pontano-sans",
});

const PinyonScriptFont = localFont({
  src: "../public/fonts/Pinyon_Script/PinyonScript-Regular.ttf",
  variable: "--font-pinyon-script",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${PontanoSansFont.variable} ${PinyonScriptFont.variable} antialiased`}
      >
        <ReactQueryProviders>
          {children}

          <DynamicTanstackDevTools />
        </ReactQueryProviders>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
