CREATE TABLE "audio_file" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"duration" real NOT NULL,
	"audio_codec" text,
	"audio_codec_profile" text,
	"bitrate" integer,
	"bitrate_mode" text,
	"sample_rate" integer NOT NULL,
	"channels" integer NOT NULL,
	"channel_layout" text,
	"bit_depth" integer,
	"container" text,
	"title" text,
	"artist" text,
	"album" text,
	"album_artist" text,
	"composer" text,
	"genre" text,
	"year" integer,
	"track_number" integer,
	"total_tracks" integer,
	"disc_number" integer,
	"total_discs" integer,
	"comment" text,
	"lyrics" text,
	"language" text,
	"has_album_art" boolean DEFAULT false NOT NULL,
	"album_art_path" text,
	"album_art_mime_type" text,
	"average_volume" real,
	"peak_volume" real,
	"dynamic_range" real,
	"loudness_lufs" real,
	"waveform_path" text,
	"waveform_data" jsonb,
	"is_processed" boolean DEFAULT false NOT NULL,
	"processing_started_at" timestamp,
	"processing_completed_at" timestamp,
	"processing_error" text,
	"needs_transcoding" boolean DEFAULT false NOT NULL,
	"transcoding_started_at" timestamp,
	"transcoding_completed_at" timestamp,
	"transcoding_error" text,
	"variants" jsonb,
	"copyright" text,
	"isrc" text,
	"publisher" text,
	"is_podcast" boolean DEFAULT false NOT NULL,
	"podcast_title" text,
	"episode_number" integer,
	"season_number" integer,
	"replay_gain_track" real,
	"replay_gain_album" real,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "file" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" text NOT NULL,
	"content_id" uuid NOT NULL,
	"file_path" text NOT NULL,
	"filename" text NOT NULL,
	"stored_filename" text NOT NULL,
	"mime_type" text NOT NULL,
	"size" integer NOT NULL,
	"extension" text,
	"md5_hash" text,
	"sha256_hash" text,
	"uploaded_by" text,
	"uploaded_at" timestamp DEFAULT now() NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp,
	"deleted_by" text,
	"is_public" boolean DEFAULT false NOT NULL,
	"permissions" jsonb,
	"title" text,
	"description" text,
	"tags" jsonb,
	"metadata" jsonb,
	"version" integer DEFAULT 1 NOT NULL,
	"previous_version_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "file_file_path_unique" UNIQUE("file_path")
);
--> statement-breakpoint
CREATE TABLE "image_file" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"aspect_ratio" real,
	"format" text,
	"color_space" text,
	"bit_depth" integer,
	"has_alpha" boolean,
	"quality" integer,
	"is_progressive" boolean,
	"is_animated" boolean,
	"frame_count" integer,
	"dominant_colors" jsonb,
	"average_color" text,
	"brightness" real,
	"contrast" real,
	"exif_data" jsonb,
	"camera_model" text,
	"camera_make" text,
	"lens_model" text,
	"focal_length" real,
	"aperture" real,
	"shutter_speed" text,
	"iso" integer,
	"flash_used" boolean,
	"latitude" real,
	"longitude" real,
	"altitude" real,
	"gps_timestamp" timestamp,
	"date_taken" timestamp,
	"orientation" integer,
	"is_processed" boolean DEFAULT false NOT NULL,
	"processing_started_at" timestamp,
	"processing_completed_at" timestamp,
	"processing_error" text,
	"thumbnail_path" text,
	"thumbnail_small_path" text,
	"thumbnail_medium_path" text,
	"thumbnail_large_path" text,
	"variants" jsonb,
	"alt_text" text,
	"caption" text,
	"copyright" text,
	"artist" text,
	"credit" text,
	"source" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "text_file" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"format" text,
	"encoding" text DEFAULT 'utf-8' NOT NULL,
	"has_bom" boolean,
	"line_ending" text,
	"line_count" integer,
	"word_count" integer,
	"character_count" integer,
	"character_count_no_spaces" integer,
	"language" text,
	"language_confidence" real,
	"content_type" text,
	"is_code" boolean,
	"programming_language" text,
	"syntax_highlighting_language" text,
	"lines_of_code" integer,
	"comment_lines" integer,
	"blank_lines" integer,
	"is_markdown" boolean,
	"markdown_headings" jsonb,
	"markdown_links" jsonb,
	"is_json" boolean,
	"json_valid" boolean,
	"json_schema" jsonb,
	"is_csv" boolean,
	"csv_delimiter" text,
	"csv_header_row" boolean,
	"csv_columns" jsonb,
	"csv_row_count" integer,
	"is_xml" boolean,
	"is_html" boolean,
	"xml_valid" boolean,
	"html_valid" boolean,
	"preview" text,
	"preview_length" integer,
	"full_text" text,
	"search_vector" text,
	"is_processed" boolean DEFAULT false NOT NULL,
	"processing_started_at" timestamp,
	"processing_completed_at" timestamp,
	"processing_error" text,
	"reading_time" integer,
	"complexity" real,
	"sentiment" text,
	"sentiment_score" real,
	"keywords" jsonb,
	"topics" jsonb,
	"title" text,
	"description" text,
	"author" text,
	"copyright" text,
	"license" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_file" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"aspect_ratio" text,
	"duration" real NOT NULL,
	"frame_rate" real,
	"total_frames" integer,
	"video_codec" text,
	"video_codec_profile" text,
	"video_bitrate" integer,
	"pixel_format" text,
	"color_space" text,
	"color_range" text,
	"bit_depth" integer,
	"has_audio" boolean DEFAULT true NOT NULL,
	"audio_codec" text,
	"audio_bitrate" integer,
	"audio_channels" integer,
	"audio_sample_rate" integer,
	"audio_language" text,
	"container" text,
	"is_processed" boolean DEFAULT false NOT NULL,
	"processing_started_at" timestamp,
	"processing_completed_at" timestamp,
	"processing_progress" real,
	"processing_error" text,
	"processing_logs" text,
	"needs_transcoding" boolean DEFAULT false NOT NULL,
	"transcoding_started_at" timestamp,
	"transcoding_completed_at" timestamp,
	"transcoding_progress" real,
	"transcoding_error" text,
	"thumbnail_path" text,
	"thumbnail_timestamp" real,
	"preview_gif_path" text,
	"sprite_sheet_path" text,
	"is_hdr" boolean,
	"hdr_format" text,
	"is_4k" boolean,
	"is_8k" boolean,
	"has_subtitles" boolean DEFAULT false NOT NULL,
	"subtitle_tracks" jsonb,
	"has_chapters" boolean DEFAULT false NOT NULL,
	"chapters" jsonb,
	"is_streamable" boolean DEFAULT false NOT NULL,
	"hls_manifest_path" text,
	"dash_manifest_path" text,
	"variants" jsonb,
	"title" text,
	"description" text,
	"copyright" text,
	"artist" text,
	"director" text,
	"producer" text,
	"studio" text,
	"content_rating" text,
	"age_restriction" integer,
	"scene_detection" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
