// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makePostRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as UserRoute from "@/app/(user)/page.info";
import * as UserAppLayoutCalendarRoute from "@/app/(user)/(app)/(layout)/calendar/page.info";
import * as UserAppLayoutCapsulesRoute from "@/app/(user)/(app)/(layout)/capsules/page.info";
import * as UserAppLayoutCapsulesIdRoute from "@/app/(user)/(app)/(layout)/capsules/[id]/page.info";
import * as UserAppLayoutCapsulesDateDateRoute from "@/app/(user)/(app)/(layout)/capsules/date/[date]/page.info";
import * as UserAppLayoutHomeRoute from "@/app/(user)/(app)/(layout)/home/page.info";
import * as UserLoginRoute from "@/app/(user)/login/page.info";
import * as PresentationRoute from "@/app/(user)/presentation/page.info";
import * as UserRegisterRoute from "@/app/(user)/register/page.info";
import * as AdminRoute from "@/app/admin/page.info";
import * as AdminCapsulesRoute from "@/app/admin/capsules/page.info";
import * as AdminCapsulesIdRoute from "@/app/admin/capsules/[id]/page.info";
import * as AdminCapsulesIdEditRoute from "@/app/admin/capsules/[id]/edit/page.info";
import * as AdminCapsulesEditIdRoute from "@/app/admin/capsules/edit/[id]/page.info";
import * as AdminUsersRoute from "@/app/admin/users/page.info";
import * as AdminUsersIdRoute from "@/app/admin/users/[id]/page.info";
import * as AdminUsersIdEditRoute from "@/app/admin/users/[id]/edit/page.info";
import * as ApiCapsulesRoute from "@/app/api/capsules/route.info";
import * as ApiCapsulesIdRoute from "@/app/api/capsules/[id]/route.info";
import * as ApiCapsulesDayDayRoute from "@/app/api/capsules/day/[day]/route.info";
import * as ApiCapsulesMonthRoute from "@/app/api/capsules/month/route.info";
import * as ApiHealthRoute from "@/app/api/health/route.info";
import * as ApiUsersRoute from "@/app/api/users/route.info";
import * as ApiUsersIdRoute from "@/app/api/users/[id]/route.info";
import * as ApiUsersLoginRoute from "@/app/api/users/login/route.info";
import * as ApiUsersMeRoute from "@/app/api/users/me/route.info";
import * as Editor00Route from "@/app/editor-00/page.info";
import * as InviteCodeRoute from "@/app/invite/[code]/page.info";
import * as MiddlewareErrorEnvRoute from "@/app/middleware/error/env/page.info";
import * as UnlockRoute from "@/app/unlock/page.info";

export const User = makeRoute(
  "/(user)",
  {
    ...defaultInfo,
    ...UserRoute.Route
  }
);
export const UserAppLayoutCalendar = makeRoute(
  "/(user)/(app)/(layout)/calendar",
  {
    ...defaultInfo,
    ...UserAppLayoutCalendarRoute.Route
  }
);
export const UserAppLayoutCapsules = makeRoute(
  "/(user)/(app)/(layout)/capsules",
  {
    ...defaultInfo,
    ...UserAppLayoutCapsulesRoute.Route
  }
);
export const UserAppLayoutCapsulesId = makeRoute(
  "/(user)/(app)/(layout)/capsules/[id]",
  {
    ...defaultInfo,
    ...UserAppLayoutCapsulesIdRoute.Route
  }
);
export const UserAppLayoutCapsulesDateDate = makeRoute(
  "/(user)/(app)/(layout)/capsules/date/[date]",
  {
    ...defaultInfo,
    ...UserAppLayoutCapsulesDateDateRoute.Route
  }
);
export const UserAppLayoutHome = makeRoute(
  "/(user)/(app)/(layout)/home",
  {
    ...defaultInfo,
    ...UserAppLayoutHomeRoute.Route
  }
);
export const UserLogin = makeRoute(
  "/(user)/login",
  {
    ...defaultInfo,
    ...UserLoginRoute.Route
  }
);
export const Presentation = makeRoute(
  "/(user)/presentation",
  {
    ...defaultInfo,
    ...PresentationRoute.Route
  }
);
export const UserRegister = makeRoute(
  "/(user)/register",
  {
    ...defaultInfo,
    ...UserRegisterRoute.Route
  }
);
export const Admin = makeRoute(
  "/admin",
  {
    ...defaultInfo,
    ...AdminRoute.Route
  }
);
export const AdminCapsules = makeRoute(
  "/admin/capsules",
  {
    ...defaultInfo,
    ...AdminCapsulesRoute.Route
  }
);
export const AdminCapsulesId = makeRoute(
  "/admin/capsules/[id]",
  {
    ...defaultInfo,
    ...AdminCapsulesIdRoute.Route
  }
);
export const AdminCapsulesIdEdit = makeRoute(
  "/admin/capsules/[id]/edit",
  {
    ...defaultInfo,
    ...AdminCapsulesIdEditRoute.Route
  }
);
export const AdminCapsulesEditId = makeRoute(
  "/admin/capsules/edit/[id]",
  {
    ...defaultInfo,
    ...AdminCapsulesEditIdRoute.Route
  }
);
export const AdminUsers = makeRoute(
  "/admin/users",
  {
    ...defaultInfo,
    ...AdminUsersRoute.Route
  }
);
export const AdminUsersId = makeRoute(
  "/admin/users/[id]",
  {
    ...defaultInfo,
    ...AdminUsersIdRoute.Route
  }
);
export const AdminUsersIdEdit = makeRoute(
  "/admin/users/[id]/edit",
  {
    ...defaultInfo,
    ...AdminUsersIdEditRoute.Route
  }
);
export const Editor00 = makeRoute(
  "/editor-00",
  {
    ...defaultInfo,
    ...Editor00Route.Route
  }
);
export const InviteCode = makeRoute(
  "/invite/[code]",
  {
    ...defaultInfo,
    ...InviteCodeRoute.Route
  }
);
export const MiddlewareErrorEnv = makeRoute(
  "/middleware/error/env",
  {
    ...defaultInfo,
    ...MiddlewareErrorEnvRoute.Route
  }
);
export const Unlock = makeRoute(
  "/unlock",
  {
    ...defaultInfo,
    ...UnlockRoute.Route
  }
);

export const getApiCapsules = makeGetRoute(
  "/api/capsules",
  {
    ...defaultInfo,
    ...ApiCapsulesRoute.Route
  },
  ApiCapsulesRoute.GET
);
export const getApiCapsulesId = makeGetRoute(
  "/api/capsules/[id]",
  {
    ...defaultInfo,
    ...ApiCapsulesIdRoute.Route
  },
  ApiCapsulesIdRoute.GET
);
export const getApiCapsulesDayDay = makeGetRoute(
  "/api/capsules/day/[day]",
  {
    ...defaultInfo,
    ...ApiCapsulesDayDayRoute.Route
  },
  ApiCapsulesDayDayRoute.GET
);
export const getApiCapsulesMonth = makeGetRoute(
  "/api/capsules/month",
  {
    ...defaultInfo,
    ...ApiCapsulesMonthRoute.Route
  },
  ApiCapsulesMonthRoute.GET
);
export const getApiHealth = makeGetRoute(
  "/api/health",
  {
    ...defaultInfo,
    ...ApiHealthRoute.Route
  },
  ApiHealthRoute.GET
);
export const getApiUsers = makeGetRoute(
  "/api/users",
  {
    ...defaultInfo,
    ...ApiUsersRoute.Route
  },
  ApiUsersRoute.GET
);
export const getApiUsersId = makeGetRoute(
  "/api/users/[id]",
  {
    ...defaultInfo,
    ...ApiUsersIdRoute.Route
  },
  ApiUsersIdRoute.GET
);
export const postApiUsersLogin = makePostRoute(
  "/api/users/login",
  {
    ...defaultInfo,
    ...ApiUsersLoginRoute.Route
  },
  ApiUsersLoginRoute.POST
);
export const postApiUsersMe = makePostRoute(
  "/api/users/me",
  {
    ...defaultInfo,
    ...ApiUsersMeRoute.Route
  },
  ApiUsersMeRoute.POST
);
